### ISSUE TITLE
Loading model weights 

### ISSUE THREAD

**Issue by ammar3010** [Shoomaher/sentiment-analysis#1]
Can you help how to load this model's saved weights in a separate .py file?

**Comment by Shoomaher** [comment]
Could you please provide more insight of what you are trying to achieve? You can call mode.save_weights and pass a path where you want to store all the model data. When you want to use saved model, simply call model constructor with your params, call model.compile and then call load_weights (instead of calling model.fit). It will restore all the features and the model is ready to use.
You can put this code into a method/function and call when you need to get your model.
